### PR TITLE
Update python version validation

### PR DESCRIPTION
**Pull request by btalanski**
Python versions weren't being properly validated and displayed in the app.

- Updated the code to make validation work
- Update Config class with methods to read/check env vars
- Add python3 env var to dockerfile

image

### CODE REVIEW

**Comment by btalanski** [comment]
> Looking good, I think there should be a config field for it though if we compare it to the other binary options:
> 
> https://github.com/MrBrax/LiveStreamDVR/blob/edac4adf1a81b7d41ea7e3b5a6be6701ef9895cf/common/ServerConfig.ts#L11

That makes sense, I can add that.

Are there features in the app that require a particular version of python ? Say one feature calls `python` binary while other calls `python3` binary ?

One more thing I'd like to understand how/where is python invoked. Can you point me to an example ?

Asking all those questions since I'm pretty now to the code base.

**Comment by MrBrax** [comment]
It does not. I don't think it actually runs python by itself anywhere.

https://github.com/MrBrax/LiveStreamDVR/blob/master/server/src/Core/Providers/Base/BaseAutomator.ts#L1046

This is how all the software is executed as far as I remember, the about page is only for system info or something.

**Comment by MrBrax** [comment]
The indentation type on the fields file seems to have changed, not sure if i had it wrong to start with

**Comment by btalanski** [comment]
> The indentation type on the fields file seems to have changed, not sure if i had it wrong to start with

Not sure either.

**Comment by btalanski** [comment]
> i actually don't know why that happens, i think it's because of the pull requests, which are one way only

Maybe merge the  commits into `develop-ts` then merge `develop-ts` into `master`. Unless there is a reason to keep those two branches separate.

**Pull request merged**
